### ISSUE TITLE
Are you gonna finish your app?

### ISSUE THREAD

**Issue by RockyLin** [behnaam/karaokeapp#1]
Hi @behnaam 

I played with your app turned out to be not finished.
I'm trying to build a Karaoke app to record  the sounds while playing a karaoke beat simultaneously from the speaker of my phone. The resulted audio file has the karaoke beat part too loud. Is there any way your Lib can help solve this problem by controlling the beat part volume properly?
Thanks a lot!

**Comment by behnaam** [comment]
This was a small project, it's based on a old android studio version too.. not very well maintained and updated tbh, it was working when the REST service still was active but I don't have that google app engine service anymore.

Regarding background noise, why not check out [NoiseCompressor](https://developer.android.com/reference/android/media/audiofx/NoiseSuppressor.html)?

[Here is a good stackoverflow answer regarding the process.](http://stackoverflow.com/a/24937499)

**Comment by RockyLin** [comment]
@behnaam Thanks! 👍
